/**
 * Root Layout Component
 *
 * This component sets up the basic layout for the entire application.
 *
 * @param {Object} props - The component props
 * @param {React.ReactNode} props.children - The child components to be rendered within the layout
 * @returns {JSX.Element} Element representing the root layout of the application
 */

import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';

// Importing Inter font with Latin subset
const inter = Inter({ subsets: ['latin'] });

// Metadata for the application
export const metadata: Metadata = {
  title: {
    template: '%s | Star Wars',
    default: 'Star Wars',
  },
  description: 'Generated by create next app',
};

// RootLayout Component
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} max-w-screen-xl mx-auto my-0`}>
        {children}
      </body>
    </html>
  );
}
